/* Automatically generated by './build/bin/build-entry.js' */

import Affix from '../packages/affix/index.js';
import Anchor from '../packages/anchor/index.js';
import AnchorLink from '../packages/anchor-link/index.js';
import Autocomplete from '../packages/autocomplete/index.js';
import Dropdown from '../packages/dropdown/index.js';
import DropdownMenu from '../packages/dropdown-menu/index.js';
import DropdownItem from '../packages/dropdown-item/index.js';
import Input from '../packages/input/index.js';
import InputNumber from '../packages/input-number/index.js';
import Checkbox from '../packages/checkbox/index.js';
import CheckboxButton from '../packages/checkbox-button/index.js';
import CheckboxGroup from '../packages/checkbox-group/index.js';
import Select from '../packages/select/index.js';
import Option from '../packages/option/index.js';
import OptionGroup from '../packages/option-group/index.js';
import Button from '../packages/button/index.js';
import ButtonGroup from '../packages/button-group/index.js';
import Table from '../packages/table/index.js';
import TableColumn from '../packages/table-column/index.js';
import TableQuery from '../packages/table-query/index.js';
import Pagination from '../packages/pagination/index.js';
import Tag from '../packages/tag/index.js';
import Alert from '../packages/alert/index.js';
import Popover from '../packages/popover/index.js';
import Tooltip from '../packages/tooltip/index.js';
import Scrollbar from '../packages/scrollbar/index.js';
import Breadcrumb from '../packages/breadcrumb/index.js';
import BreadcrumbItem from '../packages/breadcrumb-item/index.js';
import Menu from '../packages/menu/index.js';
import Row from '../packages/row/index.js';
import Submenu from '../packages/submenu/index.js';
import MenuItem from '../packages/menu-item/index.js';
import SideMenu from '../packages/side-menu/index.js';
import MenuItemGroup from '../packages/menu-item-group/index.js';
import Tabs from '../packages/tabs/index.js';
import TabPane from '../packages/tab-pane/index.js';
import Transfer from '../packages/transfer/index.js';
import TransferTree from '../packages/transfer-tree/index.js';
import Switch from '../packages/switch/index.js';
import Slider from '../packages/slider/index.js';
import Form from '../packages/form/index.js';
import FormItem from '../packages/form-item/index.js';
import Badge from '../packages/badge/index.js';
import Radio from '../packages/radio/index.js';
import RadioGroup from '../packages/radio-group/index.js';
import RadioButton from '../packages/radio-button/index.js';
import Cascader from '../packages/cascader/index.js';
import DatePicker from '../packages/date-picker/index.js';
import TimePicker from '../packages/time-picker/index.js';
import TimeSelect from '../packages/time-select/index.js';
import Tree from '../packages/tree/index.js';
import Col from '../packages/col/index.js';
import ColDrag from '../packages/col-drag/index.js';
import Header from '../packages/header/index.js';
import Footer from '../packages/footer/index.js';
import Main from '../packages/main/index.js';
import Container from '../packages/container/index.js';
import Aside from '../packages/aside/index.js';
import Layout from '../packages/layout/index.js';
import Dialog from '../packages/dialog/index.js';
import Progress from '../packages/progress/index.js';
import Upload from '../packages/upload/index.js';
import Divider from '../packages/divider/index.js';
import Collapse from '../packages/collapse/index.js';
import CollapseItem from '../packages/collapse-item/index.js';
import DescriptionList from '../packages/description-list/index.js';
import DescriptionListItem from '../packages/description-list-item/index.js';
import Message from '../packages/message/index.js';
import MessageBox from '../packages/message-box/index.js';
import Notification from '../packages/notification/index.js';
import Loading from '../packages/loading/index.js';
import Drag from '../packages/drag/index.js';
import locale from 'aui/src/locale';
import CollapseTransition from 'aui/src/transitions/collapse-transition';

const components = [
  Affix,
  Anchor,
  AnchorLink,
  Autocomplete,
  Dropdown,
  DropdownMenu,
  DropdownItem,
  Input,
  InputNumber,
  Checkbox,
  CheckboxButton,
  CheckboxGroup,
  Select,
  Option,
  OptionGroup,
  Button,
  ButtonGroup,
  Table,
  TableColumn,
  TableQuery,
  Pagination,
  Tag,
  Alert,
  Popover,
  Tooltip,
  Scrollbar,
  Breadcrumb,
  BreadcrumbItem,
  Menu,
  Row,
  Submenu,
  MenuItem,
  SideMenu,
  MenuItemGroup,
  Tabs,
  TabPane,
  Transfer,
  TransferTree,
  Switch,
  Slider,
  Form,
  FormItem,
  Badge,
  Radio,
  RadioGroup,
  RadioButton,
  Cascader,
  DatePicker,
  TimePicker,
  TimeSelect,
  Tree,
  Col,
  ColDrag,
  Header,
  Footer,
  Main,
  Container,
  Aside,
  Layout,
  Dialog,
  Progress,
  Upload,
  Divider,
  Collapse,
  CollapseItem,
  DescriptionList,
  DescriptionListItem,
  CollapseTransition
];

const install = function(Vue, opts = {}) {
  // locale.use(opts.locale);
  // locale.i18n(opts.i18n);

  components.forEach(component => {
    Vue.component(component.name, component);
  });

  Vue.use(Loading.directive);
  Vue.use(Drag.directive);

  Vue.prototype.$AUI = {
    size: opts.size || 'mini',
    zIndex: opts.zIndex || 2000
  };

  Vue.prototype.$loading = Loading.service;
  Vue.prototype.$msgbox = MessageBox;
  Vue.prototype.$alert = MessageBox.alert;
  Vue.prototype.$confirm = MessageBox.confirm;
  Vue.prototype.$notify = Notification;
  Vue.prototype.$message = Message;

};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

module.exports = {
  version: '0.0.1',
  locale: locale.use,
  i18n: locale.i18n,
  install,
  CollapseTransition,
  Loading,
  Affix,
  Anchor,
  AnchorLink,
  Autocomplete,
  Dropdown,
  DropdownMenu,
  DropdownItem,
  Input,
  InputNumber,
  Checkbox,
  CheckboxButton,
  CheckboxGroup,
  Select,
  Option,
  OptionGroup,
  Button,
  ButtonGroup,
  Table,
  TableColumn,
  TableQuery,
  Pagination,
  Tag,
  Alert,
  Popover,
  Tooltip,
  Scrollbar,
  Breadcrumb,
  BreadcrumbItem,
  Menu,
  Row,
  Submenu,
  MenuItem,
  SideMenu,
  MenuItemGroup,
  Tabs,
  TabPane,
  Transfer,
  TransferTree,
  Switch,
  Slider,
  Form,
  FormItem,
  Badge,
  Radio,
  RadioGroup,
  RadioButton,
  Cascader,
  DatePicker,
  TimePicker,
  TimeSelect,
  Tree,
  Col,
  ColDrag,
  Header,
  Footer,
  Main,
  Container,
  Aside,
  Layout,
  Dialog,
  Progress,
  Upload,
  Divider,
  Collapse,
  CollapseItem,
  DescriptionList,
  DescriptionListItem,
  Message,
  MessageBox,
  Notification,
  Drag
};

module.exports.default = module.exports;
